# https://docs.codecov.com/docs/commit-status#project-status

coverage:
  status:
    project:
      default:
        target: 0% # Make CI always succeed
        threshold: 100% # Make CI always succeed
    patch:
      default:
        target: 0% # Make CI always succeed
        threshold: 100% # Make CI always succeed

comment:
  show_carryforward_flags: true

flag_management:
  default_rules:
    carryforward: true
    statuses:
      - name_prefix: project-
        type: project
        target: 0% # Make CI always succeed
        threshold: 100% # Make CI always succeed
      - name_prefix: patch-
        type: patch
        target: 0% # Make CI always succeed
        threshold: 100% # Make CI always succeed

ignore:
  - "**/test/*"
  - "**/test/**/*"
  - "**/debug.*"

component_management:
  individual_components:
    - component_id: planning-tier-iv-maintained-packages
      name: Planning TIER IV Maintained Packages
      paths:
        - planning/autoware_costmap_generator/**
        - planning/autoware_external_velocity_limit_selector/**
        - planning/autoware_freespace_planner/**
        - planning/autoware_freespace_planning_algorithms/**
        - planning/autoware_mission_planner/**
        # - planning/autoware_objects_of_interest_marker_interface/**
        - planning/autoware_obstacle_cruise_planner/**
        # - planning/autoware_obstacle_stop_planner/**
        - planning/autoware_path_optimizer/**
        - planning/autoware_path_smoother/**
        - planning/autoware_planning_test_manager/**
        - planning/autoware_planning_topic_converter/**
        - planning/autoware_planning_validator/**
        - planning/autoware_remaining_distance_time_calculator/**
        - planning/autoware_route_handler/**
        - planning/autoware_rtc_interface/**
        - planning/autoware_scenario_selector/**
        - planning/autoware_static_centerline_generator/**
        - planning/autoware_surround_obstacle_checker/**
        - planning/autoware_velocity_smoother/**
        ##### behavior_path_planner #####
        # - planning/behavior_path_planner/autoware_behavior_path_avoidance_by_lane_change_module/**
        - planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/**
        - planning/behavior_path_planner/autoware_behavior_path_planner_common/**
        - planning/behavior_path_planner/autoware_behavior_path_start_planner_module/**
        - planning/behavior_path_planner/autoware_behavior_path_dynamic_obstacle_avoidance_module/**
        - planning/behavior_path_planner/autoware_behavior_path_lane_change_module/**
        # - planning/behavior_path_planner/autoware_behavior_path_sampling_planner_module/**
        - planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/**
        # - planning/behavior_path_planner/autoware_behavior_path_external_request_lane_change_module/**
        - planning/behavior_path_planner/autoware_behavior_path_planner/**
        - planning/behavior_path_planner/autoware_behavior_path_side_shift_module/**
        ##### behavior_velocity_planner #####
        - planning/behavior_velocity_planner/autoware_behavior_velocity_blind_spot_module/**
        - planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/**
        # - planning/behavior_velocity_planner/autoware_behavior_velocity_detection_area_module/**
        - planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/**
        # - planning/behavior_velocity_planner/autoware_behavior_velocity_no_drivable_lane_module/**
        - planning/behavior_velocity_planner/autoware_behavior_velocity_no_stopping_area_module/**
        # - planning/behavior_velocity_planner/autoware_behavior_velocity_occlusion_spot_module/**
        - planning/behavior_velocity_planner/autoware_behavior_velocity_planner/**
        # - planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/**
        - planning/behavior_velocity_planner/autoware_behavior_velocity_run_out_module/**
        # - planning/behavior_velocity_planner/autoware_behavior_velocity_speed_bump_module/**
        - planning/behavior_velocity_planner/autoware_behavior_velocity_stop_line_module/**
        # - planning/behavior_velocity_planner/autoware_behavior_velocity_template_module/**
        - planning/behavior_velocity_planner/autoware_behavior_velocity_traffic_light_module/**
        - planning/behavior_velocity_planner/autoware_behavior_velocity_virtual_traffic_light_module/**
        - planning/behavior_velocity_planner/autoware_behavior_velocity_walkway_module/**
        ##### motion_velocity_planner #####
        - planning/motion_velocity_planner/autoware_motion_velocity_dynamic_obstacle_stop_module/**
        - planning/motion_velocity_planner/autoware_motion_velocity_obstacle_velocity_limiter_module/**
        - planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/**
        - planning/motion_velocity_planner/autoware_motion_velocity_planner_common/**
        - planning/motion_velocity_planner/autoware_motion_velocity_planner_node/**

    - component_id: control-tier-iv-maintained-packages
      name: Control TIER IV Maintained Packages
      paths:
        - control/autoware_autonomous_emergency_braking/**
        - control/autoware_control_validator/**
        - control/autoware_external_cmd_selector/**
        # - control/autoware_joy_controller/**
        - control/autoware_lane_departure_checker/**
        - control/autoware_mpc_lateral_controller/**
        - control/autoware_operation_mode_transition_manager/**
        - control/autoware_pid_longitudinal_controller/**
        # - control/autoware_pure_pursuit/**
        - control/autoware_shift_decider/**
        # - control/autoware_smart_mpc_trajectory_follower/**
        - control/autoware_trajectory_follower_base/**
        - control/autoware_trajectory_follower_node/**
        - control/autoware_vehicle_cmd_gate/**
        # - control/control_performance_analysis/**
        - control/obstacle_collision_checker/**
        # - control/predicted_path_checker/**
